layout:
  qmk_keyboard: corne_rotated
  qmk_layout: LAYOUT_split_3x6_3
draw_config:
  arc_radius: 12
  # separate_combo_diagrams: true
layers:
  Combo:
    - ["", "", "", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", "", "", ""]
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
  Additional Combos:
    - ["", "", "", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", "", "", ""]
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
combos:
  - {p: [1, 2], k: "Ctrl-W", l: ["Combo"], w: 40}
  - {p: [2, 3], k: "Esc", l: ["Combo"]}
  - {p: [3, 4], k: "Tab", l: ["Combo"]}
  - {p: [1, 2, 3, 4], k: "Ctrl Alt Delete", l: ["Additional Combos"], a: top, o: 0.2, arc_scale: 1.2, slide: -0.25, w: 50, h: 45}
  - {p: [13, 14], k: "Ctrl-A", l: ["Combo"], w: 40}
  - {p: [14, 15], k: "Bspace", l: ["Combo"], w: 40}
  - {p: [15, 16], k: "Delete", l: ["Combo"], w: 40}
  - {p: [14, 15, 16], k: "Del Word", l: ["Additional Combos"], a: top, o: 0, arc_scale: 1.2, slide: -0.25, w: 35, h: 32}
  - {p: [13, 14, 15, 16], k: "Del Line", l: ["Additional Combos"], a: top, o: 0.3, arc_scale: 1.2, slide: -0.6, w: 35, h: 32}
  - {p: [16, 17], k: "New Line", l: ["Combo"], w: 35, h: 32}
  - {p: [25, 26], k: "Ctrl-Z", l: ["Combo"], w: 40}
  - {p: [26, 27], k: "Ctrl-C", l: ["Combo"], w: 40}
  - {p: [27, 28], k: "Ctrl-V", l: ["Combo"], w: 40}
  - {p: [26, 27, 28], k: "Ctrl-X", l: ["Additional Combos"], a: top, o: 0, w: 40}
  - {p: [28, 29], k: "Select Line", l: ["Combo"], w: 35, h: 32}
  - {p: [28, 31], k: "Caps Word", l: ["Additional Combos"], a: top, o: 0.15, arc_scale: 0.95, w: 35, h: 32}
  - {p: [6, 7],   k: "`", l: ["Combo"]}
  - {p: [7, 8],   k: "~", l: ["Combo"]}
  - {p: [8, 9], k: ";", l: ["Combo"]}
  - {p: [7, 8, 9], k: "+", l: ["Combo"], a: top, o: 0, arc_scale: 1, slide: -0.5}
  - {p: [18, 19], k: "_", l: ["Combo"]}
  - {p: [19, 20], k: "-", l: ["Combo"]}
  - {p: [20, 21], k: "'", l: ["Combo"]}
  - {p: [21, 22], k: "\"", l: ["Combo"]}
  - {p: [19, 20, 21], k: "=", l: ["Combo"], a: bottom, o: 0, arc_scale: 1, slide: -0.5}
  - {p: [19, 21], k: ":", l: ["Combo"], a: bottom, o: 0.4, arc_scale: 1.1, slide: 0.25}
  - {p: [33, 34], k: "../", l: ["Combo"]}
  - {p: [8, 19], k: "/", l: ["Additional Combos"], d: true}
  - {p: [8, 21], k: "\\", l: ["Additional Combos"], d: true}
  - {p: [20, 31], k: "[ {", l: ["Additional Combos"], d: true}
  - {p: [20, 33], k: "] }", l: ["Additional Combos"], d: true}
  - {p: [6, 18], k: "|", l: ["Combo"], a: left}
