layout:
  qmk_keyboard: corne_rotated
  qmk_layout: LAYOUT_split_3x6_3
draw_config:
  arc_radius: 12
  # separate_combo_diagrams: true
layers:
  DEF:
    - ["", Q, W, F, P, B, J, L, U, Y, ":", ""]
    - ["", A, R, S, T, G, M, N, E, I, O, ""]
    - ["", {h: Gui, t: Z}, {h: Alt, t: X}, {h: Ctrl, t: C}, {h: Shift, t: D}, V, K, {h: Shift, t: H}, {h: Ctrl, t: ","}, {h: Alt, t: . }, {h: Gui, t: /}, ""]
    - {h: (Sticky), t: Ctrl}
    - NUM
    - {h: DNAV,   t: Space}
    - Enter
    - CHAR
    - FUNC
combos:
  - {p: [2, 3], k: "Esc", l: ["DEF"]}
  - {p: [3, 4], k: "Tab", l: ["DEF"]}
  - {p: [7, 8],   k: "~ `", l: ["DEF"]}
  - {p: [8, 9], k: "; :", l: ["DEF"]}
  - {p: [14, 15], k: "Bspace", l: ["DEF"]}
  - {p: [15, 16], k: "Delete", l: ["DEF"]}
  - {p: [16, 17], k: "New Line", l: ["DEF"]}
  - {p: [19, 20], k: "- _", l: ["DEF"]}
  - {p: [20, 21], k: "' \"", l: ["DEF"]}
  - {p: [19, 20, 21], k: "= +", l: ["DEF"], a: top, o: 1.2, arc_scale: 1.1, slide: 0.5}
  - {p: [19, 21], k: ":", l: ["DEF"], a: top, o: 1.85, arc_scale: 1.2, slide: 0.3}
  - {p: [8, 19], k: "/", l: ["DEF"], d: true}
  - {p: [8, 21], k: "\\", l: ["DEF"], d: true}
  - {p: [20, 31], k: "[ {", l: ["DEF"], d: true}
  - {p: [20, 33], k: "] }", l: ["DEF"], d: true}
  - {p: [31, 19], k: "|", l: ["DEF"], a: left}
  - {p: [25, 26], k: "Ctrl-Z", l: ["DEF"]}
  - {p: [26, 27], k: "Ctrl-C", l: ["DEF"]}
  - {p: [27, 28], k: "Ctrl-V", l: ["DEF"]}
  - {p: [14, 15, 16], k: "Del Word", l: ["DEF"], a: top, o: 1.2, arc_scale: 1.2, slide: -0.25}
  - {p: [13, 14, 15, 16], k: "Del Line", l: ["DEF"], a: top, o: 1.5, arc_scale: 1.2, slide: -0.6}
  - {p: [26, 27, 28], k: "Ctrl-X", l: ["DEF"], a: bottom, o: 0.15}
  - {p: [28, 29], k: "Select Line", l: ["DEF"]}
  - {p: [28, 31], k: "Caps Word", l: ["DEF"], a: top, o: 0.15}
